# Generated by Django 5.0 on 2023-12-18 12:23

import django.db.models.deletion
import macaddress.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='feedback.division')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userMAC', macaddress.fields.MACAddressField(integer=False, max_length=17)),
                ('description', models.TextField(max_length=500)),
                ('incidentDate', models.DateTimeField(blank=True, null=True)),
                ('reportedDate', models.DateTimeField()),
                ('feedbackDate', models.DateTimeField()),
                ('submittedBy', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('forStation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='feedback.policestation')),
            ],
        ),
    ]
