# Generated by Django 5.0 on 2023-12-19 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='userMAC',
        ),
        migrations.AddField(
            model_name='feedback',
            name='userIP',
            field=models.GenericIPAddressField(default='192.168.0.1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='incidentDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reportedDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.UniqueConstraint(fields=('name', 'state'), name='division_unique_constraint', violation_error_message='Division Name has to be Unique in that State'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('submittedBy', 'feedbackDate'), name='feedback_repetition_protection_constraint', violation_error_message='User cannot submit multiple Feedbacks at the same time'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(check=models.Q(('incidentDate__isnull', True), ('incidentDate__lt', models.F('feedbackDate')), _connector='OR'), name='incidentDate_check_constraint', violation_error_message='Incident Date cannot be after Feedback Submission Date'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(check=models.Q(('reportedDate__isnull', True), ('reportedDate__lt', models.F('feedbackDate')), _connector='OR'), name='reportedDate_check1_constraint', violation_error_message='Reported Date cannot be after Feedback Submission Date'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(check=models.Q(('reportedDate__isnull', True), ('reportedDate__gt', models.F('incidentDate')), _connector='OR'), name='reportedDate_check2_constraint', violation_error_message='Reported Date cannot be before Incident Date'),
        ),
        migrations.AddConstraint(
            model_name='policestation',
            constraint=models.UniqueConstraint(fields=('name', 'division'), name='police_station_unique_constraint', violation_error_message='Police Station Name has to be Unique in that Division'),
        ),
    ]
