# Generated by Django 5.0 on 2023-12-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedback_usermac_feedback_userip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='experience',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
    ]
